dependencies:
 - atproto
 - click
 - codecov
 - feedgen
 - httpx
 - requests
 - twisted>=18.4.0
 - psycopg
 - pyiem>=1.26
 - pymemcache
 - pytest
 - pytest-cov
 - pytest-runner
 - pytest-twisted
 # Mocking requests
 - responses
 - service_identity
 - setuptools_scm
 # cython is a lame requirement from rabbit hole of cartopy
 - cython
 - cartopy
 - mastodon.py